# General {{{1
title: "Clássico, tradicional, eclético: Arquitetura brasileira no longo século XIX"
email: palazzo@unb.br
description: >-
  Discursos arquitetônicos produzidos de c. 1860 a 1930,
  com ênfase na formação dos campos teóricos brasileiros
  compreendidos numa abordagem global.
baseurl: "/arqtrad"
url: "https://dmcpatrimonio.github.io"
lang: pt
twitter_username: p3palazzo
github_username:  dmcpatrimonio

# Content {{{1
collections: # {{{2
  creativework:
    output   : true
    permalink: /:collection/:name
  event:
    output   : true
    permalink: /:collection/:name
  organization:
    output   : true
    permalink: /:collection/:name
  person:
    output   : true
    permalink: /:collection/:name
  place:
    output   : true
    permalink: /:collection/:name
  thing:
    output   : true
    permalink: /:collection/:name

defaults: # {{{2
  -
    scope:
      path      : ""
      type      : "person"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Person"
      class     : "Agent"
  -
    scope:
      path      : ""
      type      : "organization"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Organization"
      class     : "AgentClass"
  -
    scope:
      path      : ""
      type      : "event"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Event"
      type      : "Event"
  -
    scope:
      path      : ""
      type      : "place"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Place"
      class     : "Location"
  -
    scope:
      path      : ""
      type      : "creativework"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/CreativeWork"
      type      : "PhysicalObject"
  -
    scope:
      path      : ""
      type      : "thing"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Thing"

# Build settings {{{1
theme: minima # {{{2
minima:
  date_format : "%Y-%m-%d"
  social_links:
    twitter   : https://twitter.com/p3palazzo
    github    : https://github.com/dmcpatrimonio/arqtrad
    instagram : https://instagram.com/arqtrad
header_pages:
  - 6enanparq-intro.md
  - pibic21-projeto.md

plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown
source: docs/
relative_links:
  enabled: true
  collections: true
markdown: kramdown
kramdown:
  auto_ids: true
permalink: pretty

exclude:
  - LICENSE
  - README.md

# vim: set foldmethod=marker :
