# General {{{1
title: "Clássico, tradicional, eclético: Arquitetura brasileira no longo século XIX"
email: palazzo@unb.br
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "arqtrad"
url: "https://dmcpatrimonio.github.io"
twitter_username: p3palazzo
github_username:  p3palazzo

# Content {{{1
collections: # {{{2
  event:
    output   : true
    permalink: /:collection/:name
  intangible:
    output   : true
    permalink: /:collection/:name
  org:
    output   : true
    permalink: /:collection/:name
  person:
    output   : true
    permalink: /:collection/:name
  place:
    output   : true
    permalink: /:collection/:name
  product:
    output   : true
    permalink: /:collection/:name
  thing:
    output   : true
    permalink: /:collection/:name
  work:
    output   : true
    permalink: /:collection/:name

defaults: # {{{2
  -
    scope:
      path      : ""
      type      : "event"
    values:
      layout    : "thing"
  -
    scope:
      path      : ""
      type      : "intangible"
    values:
      layout    : "thing"
  -
    scope:
      path      : ""
      type      : "org"
    values:
      layout    : "thing"
  -
    scope:
      path      : ""
      type      : "person"
    values:
      layout    : "thing"
  -
    scope:
      path      : ""
      type      : "place"
    values:
      layout    : "thing"
  -
    scope:
      path      : ""
      type      : "product"
    values:
      layout    : "thing"
  -
    scope:
      path      : ""
      type      : "thing"
    values:
      layout    : "thing"
  -
    scope:
      path      : ""
      type      : "work"
    values:
      layout    : "thing"

# Build settings {{{1
theme: minima # {{{2
minima:
  date_format : "%Y-%m-%d"
  social_links:
    twitter   : p3palazzo
    github    : p3palazzo

plugins:
  - jekyll-feed
  - jekyll-github-metadata
markdown: kramdown
kramdown:
  auto_ids: true
exclude: # {{{2
  - docs/reveal.js/
  - README.md
  - lib/
  - spec/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - .vendor/bundle/
  - .vendor/cache/
  - .vendor/gems/
  - .vendor/ruby/

# vim: set foldmethod=marker :
